//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.EntityClient;
using System.Data.Objects;

namespace Mediaportal.TV.Server.TVDatabase.Entities
{
    public partial class Model : ObjectContext
    {
        public const string ConnectionString = "name=Model";
        public const string ContainerName = "Model";

      #region Constructors
    
      public Model()
        : base(ConnectionString, ContainerName)
      {
        Initialize();
      }
    
      public Model(string connectionString)
        : base(connectionString, ContainerName)
      {
        Initialize();
      }
    
      public Model(EntityConnection connection)
        : base(connection, ContainerName)
      {
        Initialize();
      }
    
      private void Initialize()
      {
        // Creating proxies requires the use of the ProxyDataContractResolver and
        // may allow lazy loading which can expand the loaded graph during serialization.
        ContextOptions.ProxyCreationEnabled = false;
        ObjectMaterialized += new ObjectMaterializedEventHandler(HandleObjectMaterialized);
      }
    
      private void HandleObjectMaterialized(object sender, ObjectMaterializedEventArgs e)
      {
        var entity = e.Entity as IObjectWithChangeTracker;
        if (entity != null)
        {
          bool changeTrackingEnabled = entity.ChangeTracker.ChangeTrackingEnabled;
          try
          {
            entity.MarkAsUnchanged();
          }
          finally
          {
            entity.ChangeTracker.ChangeTrackingEnabled = changeTrackingEnabled;
          }
          this.StoreReferenceKeyValues(entity);
        }
      }
    
      #endregion

      #region ObjectSet Properties

      private ObjectSet<CanceledSchedule> _canceledSchedules;
      private ObjectSet<CardGroupMap> _cardGroupMaps;
      private ObjectSet<CardGroup> _cardGroups;

      private ObjectSet<Card> _cards;
      private ObjectSet<ChannelGroup> _channelGroups;
      private ObjectSet<ChannelLinkageMap> _channelLinkageMaps;
      private ObjectSet<ChannelMap> _channelMaps;
      private ObjectSet<Channel> _channels;
      private ObjectSet<Conflict> _conflicts;
      private ObjectSet<DisEqcMotor> _disEqcMotors;
      private ObjectSet<Favorite> _favorites;
      private ObjectSet<GroupMap> _groupMaps;
      private ObjectSet<History> _histories;
      private ObjectSet<KeywordMap> _keywordMaps;
      private ObjectSet<Keyword> _keywords;
      private ObjectSet<LnbType> _lnbTypes;
      private ObjectSet<PendingDeletion> _pendingDeletions;
      private ObjectSet<PersonalTVGuideMap> _personalTVGuideMaps;
      private ObjectSet<ProgramCategory> _programCategories;
      private ObjectSet<ProgramCredit> _programCredits;
      private ObjectSet<Program> _programs;
      private ObjectSet<RecordingCredit> _recordingCredits;
      private ObjectSet<Recording> _recordings;
      private ObjectSet<RuleBasedSchedule> _ruleBasedSchedules;
      private ObjectSet<Satellite> _satellites;
      private ObjectSet<ScheduleRulesTemplate> _scheduleRulesTemplates;
      private ObjectSet<Schedule> _schedules;
      private ObjectSet<Setting> _settings;
      private ObjectSet<SoftwareEncoder> _softwareEncoders;
      private ObjectSet<Timespan> _timespans;
      private ObjectSet<TuningDetail> _tuningDetails;
      private ObjectSet<TvMovieMapping> _tvMovieMappings;
      private ObjectSet<Version> _versions;

      public ObjectSet<CanceledSchedule> CanceledSchedules
      {
        get { return _canceledSchedules  ?? (_canceledSchedules = CreateObjectSet<CanceledSchedule>("CanceledSchedules")); }
      }

      public ObjectSet<Card> Cards
      {
        get { return _cards  ?? (_cards = CreateObjectSet<Card>("Cards")); }
      }

      public ObjectSet<CardGroup> CardGroups
      {
        get { return _cardGroups  ?? (_cardGroups = CreateObjectSet<CardGroup>("CardGroups")); }
      }

      public ObjectSet<CardGroupMap> CardGroupMaps
      {
        get { return _cardGroupMaps  ?? (_cardGroupMaps = CreateObjectSet<CardGroupMap>("CardGroupMaps")); }
      }

      public ObjectSet<Channel> Channels
      {
        get { return _channels  ?? (_channels = CreateObjectSet<Channel>("Channels")); }
      }

      public ObjectSet<ChannelGroup> ChannelGroups
      {
        get { return _channelGroups  ?? (_channelGroups = CreateObjectSet<ChannelGroup>("ChannelGroups")); }
      }

      public ObjectSet<ChannelLinkageMap> ChannelLinkageMaps
      {
        get { return _channelLinkageMaps  ?? (_channelLinkageMaps = CreateObjectSet<ChannelLinkageMap>("ChannelLinkageMaps")); }
      }

      public ObjectSet<ChannelMap> ChannelMaps
      {
        get { return _channelMaps  ?? (_channelMaps = CreateObjectSet<ChannelMap>("ChannelMaps")); }
      }

      public ObjectSet<Conflict> Conflicts
      {
        get { return _conflicts  ?? (_conflicts = CreateObjectSet<Conflict>("Conflicts")); }
      }

      public ObjectSet<DisEqcMotor> DisEqcMotors
      {
        get { return _disEqcMotors  ?? (_disEqcMotors = CreateObjectSet<DisEqcMotor>("DisEqcMotors")); }
      }

      public ObjectSet<Favorite> Favorites
      {
        get { return _favorites  ?? (_favorites = CreateObjectSet<Favorite>("Favorites")); }
      }

      public ObjectSet<GroupMap> GroupMaps
      {
        get { return _groupMaps  ?? (_groupMaps = CreateObjectSet<GroupMap>("GroupMaps")); }
      }

      public ObjectSet<History> Histories
      {
        get { return _histories  ?? (_histories = CreateObjectSet<History>("Histories")); }
      }

      public ObjectSet<Keyword> Keywords
      {
        get { return _keywords  ?? (_keywords = CreateObjectSet<Keyword>("Keywords")); }
      }

      public ObjectSet<KeywordMap> KeywordMaps
      {
        get { return _keywordMaps  ?? (_keywordMaps = CreateObjectSet<KeywordMap>("KeywordMaps")); }
      }

      public ObjectSet<PendingDeletion> PendingDeletions
      {
        get { return _pendingDeletions  ?? (_pendingDeletions = CreateObjectSet<PendingDeletion>("PendingDeletions")); }
      }

      public ObjectSet<PersonalTVGuideMap> PersonalTVGuideMaps
      {
        get { return _personalTVGuideMaps  ?? (_personalTVGuideMaps = CreateObjectSet<PersonalTVGuideMap>("PersonalTVGuideMaps")); }
      }

      public ObjectSet<Program> Programs
      {
        get { return _programs  ?? (_programs = CreateObjectSet<Program>("Programs")); }
      }

      public ObjectSet<ProgramCategory> ProgramCategories
      {
        get { return _programCategories  ?? (_programCategories = CreateObjectSet<ProgramCategory>("ProgramCategories")); }
      }

      public ObjectSet<ProgramCredit> ProgramCredits
      {
        get { return _programCredits  ?? (_programCredits = CreateObjectSet<ProgramCredit>("ProgramCredits")); }
      }

      public ObjectSet<Recording> Recordings
      {
        get { return _recordings  ?? (_recordings = CreateObjectSet<Recording>("Recordings")); }
      }

      public ObjectSet<RuleBasedSchedule> RuleBasedSchedules
      {
        get { return _ruleBasedSchedules  ?? (_ruleBasedSchedules = CreateObjectSet<RuleBasedSchedule>("RuleBasedSchedules")); }
      }

      public ObjectSet<Satellite> Satellites
      {
        get { return _satellites  ?? (_satellites = CreateObjectSet<Satellite>("Satellites")); }
      }

      public ObjectSet<Schedule> Schedules
      {
        get { return _schedules  ?? (_schedules = CreateObjectSet<Schedule>("Schedules")); }
      }

      public ObjectSet<ScheduleRulesTemplate> ScheduleRulesTemplates
      {
        get { return _scheduleRulesTemplates  ?? (_scheduleRulesTemplates = CreateObjectSet<ScheduleRulesTemplate>("ScheduleRulesTemplates")); }
      }

      public ObjectSet<Setting> Settings
      {
        get { return _settings  ?? (_settings = CreateObjectSet<Setting>("Settings")); }
      }

      public ObjectSet<SoftwareEncoder> SoftwareEncoders
      {
        get { return _softwareEncoders  ?? (_softwareEncoders = CreateObjectSet<SoftwareEncoder>("SoftwareEncoders")); }
      }

      public ObjectSet<Timespan> Timespans
      {
        get { return _timespans  ?? (_timespans = CreateObjectSet<Timespan>("Timespans")); }
      }

      public ObjectSet<TuningDetail> TuningDetails
      {
        get { return _tuningDetails  ?? (_tuningDetails = CreateObjectSet<TuningDetail>("TuningDetails")); }
      }

      public ObjectSet<TvMovieMapping> TvMovieMappings
      {
        get { return _tvMovieMappings  ?? (_tvMovieMappings = CreateObjectSet<TvMovieMapping>("TvMovieMappings")); }
      }

      public ObjectSet<Version> Versions
      {
        get { return _versions  ?? (_versions = CreateObjectSet<Version>("Versions")); }
      }

      public ObjectSet<LnbType> LnbTypes
      {
        get { return _lnbTypes  ?? (_lnbTypes = CreateObjectSet<LnbType>("LnbTypes")); }
      }

      public ObjectSet<RecordingCredit> RecordingCredits
      {
        get { return _recordingCredits  ?? (_recordingCredits = CreateObjectSet<RecordingCredit>("RecordingCredits")); }
      }

      #endregion
    }
}
